#! /bin/bash

startdir=$(pwd)


function has-apt() {
for i in "$@"
do
  if has-dpkg? $i ; then
     echo $i already installed
  else
     sudo apt-get install -y -q $i
  fi
done
}

function has-dpkg?() {
  dpkg -l $1 >/dev/null 2>/dev/null
}

function symlink() {
  if [ -f $2 ]; then
     echo $2 exists
  else
     ln -s $1 $2
  fi
}

function file-source() {
   if [ -f $1 ]; then
     echo $1 already exists
   else 
     wget $2
   fi

}

function has-source-pkg() {
   file-source $1.tar.gz $2
   if ! [ -d $1 ]; then
       tar xfz $1.tar.gz
       cd $1
       ./configure
       make
       sudo checkinstall -y
       cd $startdir
   fi
}

function git-source() {
   if [ -d $1 ]; then
     echo $1 already exists
   else 
     git clone $2
   fi
}

function has-cabal-install?() {
   type -P cabal >/dev/null
}

function haskell-platform() {
   if has-cabal-install? ; then
      echo haskell-platform probably already installed
      return 0
   fi

   if karmic? ; then
      has-apt ghc6 ghc6-prof ghc6-doc haddock libglut-dev happy alex
      has-apt libedit-dev zlib1g-dev checkinstall

      cd $startdir
      file-source haskell-platform-2009.2.0.2.tar.gz http://hackage.haskell.org/platform/2009.2.0.2/haskell-platform-2009.2.0.2.tar.gz
      tar -xzf haskell-platform-2009.2.0.2.tar.gz
      cd haskell-platform-2009.2.0.2
 
      # Build & Install
      ./configure
      make
      sudo checkinstall -y
      cd $startdir
      sudo cabal update
   fi

}

function cabal-git-source() {
   if [ -d $1 ]; then
     echo $1 already exists
   else 
     git clone $2
     cd $1
     sudo cabal install --global -p --enable-documentation
     cd $startdir
   fi
}

function up-to-date () {
   sudo apt-get update
   sudo apt-get upgrade
   if has-cabal-install? ; then
      sudo cabal update
   fi 
}

function karmic?() {
   if [ -z $(grep CODENAME=karmic /etc/lsb-release) ]; then
      return 1
   else
      return 0
   fi
}
  
function lucid?() {
   if [ -z $(grep CODENAME=lucid /etc/lsb-release) ]; then
      return 1
   else
      return 0
   fi
}

function has-cabal-pkg () {
for i in "$@"
do
   if [ -z "$(ghc-pkg list | grep $i)" ]; then
      sudo cabal install $i --global -p --enable-documentation
   fi
done
}

if [ -z "$@" ]; then
  if [ -f .desysad ]; then
    . .desysad
  elif [ -f ~/.desysad ]; then
    . ~/.desysad
  fi
else 
  for i in "$@"
  do
     $i
  done
fi
